In [41]:
import numpy as np

test = np.array([[1,2,3],[4,5,6],[7,8,9]])
train = np.array([[4,5,6],[7,8,9],[1,2,3],[1,2,3],[4,5,6]])

num_test = test.shape[0]
num_train = train.shape[0]

dists = np.zeros((num_test,num_train))
for i in xrange(num_test):
    for j in xrange(num_train):
        tmp = test[i,:] - train[j,:]
        print tmp
        dists[i,j] = np.sqrt(np.dot(tmp,tmp));
        
print dists

v = np.tile(test[0,:], [num_train,1])
print v

[-3 -3 -3]
[-6 -6 -6]
[0 0 0]
[0 0 0]
[-3 -3 -3]
[0 0 0]
[-3 -3 -3]
[3 3 3]
[3 3 3]
[0 0 0]
[3 3 3]
[0 0 0]
[6 6 6]
[6 6 6]
[3 3 3]
[[  5.19615242  10.39230485   0.           0.           5.19615242]
 [  0.           5.19615242   5.19615242   5.19615242   0.        ]
 [  5.19615242   0.          10.39230485  10.39230485   5.19615242]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
a = np.arange(6)

a = a.reshape([2,3])
print a 

idx = [1,2]

print a[:,idx]

[[0 1 2]
 [3 4 5]]
[[1 2]
 [4 5]]


In [86]:
from collections import Counter

a = np.arange(6).reshape([3,2])
print a

b = np.array([1,1])
print a+b

[[0 1]
 [2 3]
 [4 5]]
[[1 2]
 [3 4]
 [5 6]]


In [99]:
a = np.array([[1,2,3], [1, 0, -1], [-2,-2,-2]])
b = [0,1,2]

print a[np.arange(3),b]

[ 1  0 -2]


In [126]:
def svm_loss_vectorized(W, X, y, reg):
  """
  Structured SVM loss function, vectorized implementation.

  Inputs and outputs are the same as svm_loss_naive.
  """
  loss = 0.0
  dW = np.zeros(W.shape) # initialize the gradient as zero
  num_trains = X.shape[0]
  print num_trains
  #############################################################################
  # TODO:                                                                     #
  # Implement a vectorized version of the structured SVM loss, storing the    #
  # result in loss.                                                           #
  #############################################################################
  scores = X.dot(W)
  print scores
  tmp = np.matrix(scores[np.arange(num_trains),y])
  print tmp
  print tmp.T.shape
  print scores.shape
  subs = scores - tmp.T + 1
  print subs
  loss = np.sum(subs[subs > 0])
  print loss
  loss = loss/num_trains
  print loss
  #############################################################################
  #                             END OF YOUR CODE                              #
  #############################################################################

X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
W = np.ones([4,3])
y = [0,1,2]


print np.sum(X>5,axis=1)

X[np.arange(3),[0,1,2]] += np.sum(X>5,axis=1) -1
print X
print X[np.arange(3),y].shape
X[np.arange(3),y] *= (-1)
print X

print np.maximum(X,0)

[0 3 4]
[[ 0  2  3  4]
 [ 5  8  7  8]
 [ 9 10 14 12]]
(3,)
[[  0   2   3   4]
 [  5  -8   7   8]
 [  9  10 -14  12]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]]
