In [4]:
import numpy as np

a = np.arange(9).reshape((3,3))
print a

index = np.argmax(a)
print index

[[0 1 2]
 [3 4 5]
 [6 7 8]]
8


In [1]:
import numpy as np

weight_scales = np.logspace(-4, 0, num=20)

print weight_scales


[  1.00000000e-04   1.62377674e-04   2.63665090e-04   4.28133240e-04
   6.95192796e-04   1.12883789e-03   1.83298071e-03   2.97635144e-03
   4.83293024e-03   7.84759970e-03   1.27427499e-02   2.06913808e-02
   3.35981829e-02   5.45559478e-02   8.85866790e-02   1.43844989e-01
   2.33572147e-01   3.79269019e-01   6.15848211e-01   1.00000000e+00]
